.TH utf8lookup 1 "June, 2006"
.SH NAME
utf8lookup \- Look up Unicode characters from the command line
.SH SYNOPSIS
.B utf8lookup <unicode codepoint as hex text without leading 0x>
.SH DESCRIPTION
.I utf8lookup
is a simple bash script that will read a Unicode codepoint as hex without the leading 0x and print out the name of the corresponding character.
.SH SEE ALSO
uniname
.SH REFERENCES
Unicode Standard, version 4.1
.SH AUTHOR
This manual page was written for the Debian GNU/Linux distribution because the original program does not have a manual page.
.PP
This manual page was written by Mohammed Sameer <debian@foolab.org>, for the Debian GNU/Linux system (but may be used by others).
.SH LICENSE
GNU General Public License
